export const difficultyLevel = ['Any', 'Difficulty', 'Easy', 'Medium', 'Hard'];

// Quiz Categories
export const quizCategories = [
  'General Knowledge',
  'Entertainment: Books',
  'Entertainment: Film',
  'Entertainment: Music',
  'Entertainment: Musical & Theaters',
  'Entertainment: Television',
  'Entertainment: Video Games',
  'Entertainment: Board Games ',
  'Science & Nature',
  'Science: Computers',
  'Science: Mathematics',
  'Mythology',
  'Sports',
  'Geography',
  'History',
  'Politics',
  'Art',
  'Celebrities',
  'Animals',
  'Vehicles',
  'Entertainment',
  'Science',
  'Entertainment: Comics',
  'Entertainment: Gadgets',
  'Entertainment: Japanese Anime & Manga',
  'Entertainment: Cartoon & Animations',
];
