export { default as AnimatedText } from './AnimatedText';
export { default as Box } from './Box';
export { default as Button } from './Button';
export { default as CountDown } from './CountDown';
export { default as DropDown } from './DropDown';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Input } from './Input';
export { default as InstructionsModule } from './InstructionsModule';
export { default as Loader } from './Loader';
export { default as PageTemplate } from './PageTemplate';
export { default as PopUp } from './PopUp';
export { default as ProgressBar } from './ProgressBar';
export { default as QuizChoiceOptions } from './QuizChoiceOptions';
export { default as QuizTemplate } from './QuizTemplate';
export { default as ToggleTheme } from './ToggleTheme';
export { default as Table } from './Table';
export { default as Form } from './SetupQuizForm'